files:
  - filename: OpenAi.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    download_location: ./config/Ruleset/
  - filename: Claude.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Claude.list
    download_location: ./config/Ruleset/
  - filename: Apple.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Apple.list
    download_location: ./config/Ruleset/
  - filename: Bahamut.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
    download_location: ./config/Ruleset/
  - filename: BilibiliHMT.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
    download_location: ./config/Ruleset/
  - filename: Bilibili.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
    download_location: ./config/Ruleset/
  - filename: ChinaMedia.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
    download_location: ./config/Ruleset/cn/
  - filename: Download.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
    download_location: ./config/Ruleset/cn/
  - filename: ChinaCompanyIp.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    download_location: ./config/Ruleset/cn/
  - filename: ChinaDomain.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    download_location: ./config/Ruleset/cn/
  - filename: ChinaIp.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
    download_location: ./config/Ruleset/cn/
  - filename: NetEaseMusic.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
    download_location: ./config/Ruleset/
  - filename: Epic.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
    download_location: ./config/Ruleset/
  - filename: Origin.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
    download_location: ./config/Ruleset/
  - filename: Sony.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
    download_location: ./config/Ruleset/
  - filename: Steam.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
    download_location: ./config/Ruleset/
  - filename: Nintendo.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
    download_location: ./config/Ruleset/
  - filename: OneDrive.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
    download_location: ./config/Ruleset/
  - filename: Bing.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
    download_location: ./config/Ruleset/
  - filename: GoogleFCM.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
    download_location: ./config/Ruleset/
  - filename: Telegram.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Telegram.list
    download_location: ./config/Ruleset/
  - filename: ProxyGFWlist.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
    download_location: ./config/Ruleset/
  - filename: ProxyMedia.list
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
    download_location: ./config/Ruleset/
